### ISSUE TITLE
"Tiles Plugin Sample app" link is not working

### ISSUE THREAD

**Issue by CezaryDanielNowak** [andreszs/cordova-plugin-tiles#2]
"Tiles Plugin Sample app" link from the readme is not working

**Comment by andreszs** [comment]
The link is now working again: **[Get Tiles Plugin Sample](https://www.microsoft.com/en-us/p/tiles-plugin-sample/9nkz4fzh6bfq?activetab=pivot:overviewtab)**

**Notice** this app is not listed in the store search results, you must use the direct link to locate and install it, because it's a testing / developer-related app. That's the reason why it was previosly deactivated from the store, but this has been fixed now.
